use autoangel_core::util::data_source::DataSource;
use wasm_bindgen::prelude::*;

/// Parse a GFX (visual effect) file from bytes. Returns a
/// `GfxEffect` — TypeScript types are generated by `tsify-next` from
/// the Rust definitions in `autoangel_core::model::gfx`.
#[wasm_bindgen(js_name = "parseGfx")]
pub fn parse_gfx(data: &[u8]) -> Result<autoangel_core::model::gfx::GfxEffect, JsError> {
    autoangel_core::model::gfx::GfxEffect::parse(data).map_err(|e| crate::format_error(&e))
}

/// Parsed ECM (composite model) file.
#[wasm_bindgen]
pub struct EcmModel {
    inner: autoangel_core::model::ecm::EcmModel,
}

#[wasm_bindgen]
impl EcmModel {
    /// Parse an ECM file from bytes.
    #[wasm_bindgen]
    pub fn parse(data: &[u8]) -> Result<EcmModel, JsError> {
        let inner = autoangel_core::model::ecm::EcmModel::parse(data)
            .map_err(|e| crate::format_error(&e))?;
        Ok(EcmModel { inner })
    }

    /// Path to the skin model (.SMD).
    #[wasm_bindgen(getter, js_name = "skinModelPath")]
    pub fn skin_model_path(&self) -> String {
        self.inner.skin_model_path.clone()
    }

    /// ECM version number.
    #[wasm_bindgen(getter)]
    pub fn version(&self) -> u32 {
        self.inner.version
    }

    /// Additional skin paths referenced by this model.
    #[wasm_bindgen(getter, js_name = "additionalSkins")]
    pub fn additional_skins(&self) -> Vec<String> {
        self.inner.additional_skins.clone()
    }

    /// Whether BoneScaleEx (new) format is used for bone scaling.
    #[wasm_bindgen(getter, js_name = "newBoneScale")]
    pub fn new_bone_scale(&self) -> bool {
        self.inner.new_bone_scale
    }

    /// Number of bone scale entries.
    #[wasm_bindgen(getter, js_name = "boneScaleCount")]
    pub fn bone_scale_count(&self) -> usize {
        self.inner.bone_scales.len()
    }

    /// Returns `undefined` if `i` is out of bounds.
    #[wasm_bindgen(js_name = "getBoneScale")]
    pub fn get_bone_scale(&self, i: usize) -> Option<autoangel_core::model::ecm::BoneScaleEntry> {
        self.inner.bone_scales.get(i).cloned()
    }

    /// Bone name used for foot offset calculation.
    #[wasm_bindgen(getter, js_name = "scaleBaseBone")]
    pub fn scale_base_bone(&self) -> Option<String> {
        self.inner.scale_base_bone.clone()
    }

    /// Default animation playback speed.
    #[wasm_bindgen(getter, js_name = "defPlaySpeed")]
    pub fn def_play_speed(&self) -> f32 {
        self.inner.def_play_speed
    }

    /// Number of child model attachments.
    #[wasm_bindgen(getter, js_name = "childCount")]
    pub fn child_count(&self) -> usize {
        self.inner.child_models.len()
    }

    /// Returns `undefined` if `i` is out of bounds.
    #[wasm_bindgen(js_name = "getChild")]
    pub fn get_child(&self, i: usize) -> Option<autoangel_core::model::ecm::ChildModel> {
        self.inner.child_models.get(i).cloned()
    }

    // Combined actions

    /// Number of combined actions defined in this ECM.
    #[wasm_bindgen(getter, js_name = "combineActionCount")]
    pub fn combine_action_count(&self) -> usize {
        self.inner.combine_actions.len()
    }

    /// Name of the combined action at the given index.
    #[wasm_bindgen(js_name = "combineActionName")]
    pub fn combine_action_name(&self, i: usize) -> Option<String> {
        self.inner.combine_actions.get(i).map(|a| a.name.clone())
    }

    /// Loop count of the combined action at the given index.
    #[wasm_bindgen(js_name = "combineActionLoopCount")]
    pub fn combine_action_loop_count(&self, i: usize) -> i32 {
        self.inner
            .combine_actions
            .get(i)
            .map_or(0, |a| a.loop_count)
    }

    /// Number of events in the combined action at the given index.
    #[wasm_bindgen(js_name = "combineActionEventCount")]
    pub fn combine_action_event_count(&self, i: usize) -> usize {
        self.inner
            .combine_actions
            .get(i)
            .map_or(0, |a| a.events.len())
    }

    /// Number of base actions in the combined action at the given index.
    #[wasm_bindgen(js_name = "combineActionBaseActionCount")]
    pub fn combine_action_base_action_count(&self, i: usize) -> usize {
        self.inner
            .combine_actions
            .get(i)
            .map_or(0, |a| a.base_actions.len())
    }

    /// Name of the base action at (action_idx, base_idx).
    #[wasm_bindgen(js_name = "combineActionBaseActionName")]
    pub fn combine_action_base_action_name(
        &self,
        action_idx: usize,
        base_idx: usize,
    ) -> Option<String> {
        self.inner
            .combine_actions
            .get(action_idx)
            .and_then(|a| a.base_actions.get(base_idx))
            .map(|b| b.name.clone())
    }

    // Events within combined actions (double-indexed)

    /// Returns `undefined` if either index is out of bounds.
    #[wasm_bindgen(js_name = "getEvent")]
    pub fn get_event(
        &self,
        action_idx: usize,
        event_idx: usize,
    ) -> Option<autoangel_core::model::ecm::EcmEvent> {
        self.inner
            .combine_actions
            .get(action_idx)
            .and_then(|a| a.events.get(event_idx))
            .cloned()
    }

    // CoGfx persistent events

    /// Number of persistent CoGfx events attached to this ECM.
    #[wasm_bindgen(getter, js_name = "coGfxCount")]
    pub fn co_gfx_count(&self) -> usize {
        self.inner.co_gfx.len()
    }

    /// FX file path for the CoGfx event at the given index.
    #[wasm_bindgen(js_name = "coGfxFxFilePath")]
    pub fn co_gfx_fx_file_path(&self, i: usize) -> Option<String> {
        self.inner.co_gfx.get(i).map(|e| e.fx_file_path.clone())
    }
}

/// Parsed SMD (skin model data) file.
#[wasm_bindgen]
pub struct SmdModel {
    inner: autoangel_core::model::smd::SmdModel,
}

#[wasm_bindgen]
impl SmdModel {
    /// Parse an SMD file from bytes.
    #[wasm_bindgen]
    pub fn parse(data: &[u8]) -> Result<SmdModel, JsError> {
        let ds = DataSource::from_bytes(data.to_vec());
        let inner = pollster::block_on(autoangel_core::model::smd::SmdModel::parse(&ds))
            .map_err(|e| crate::format_error(&e))?;
        Ok(SmdModel { inner })
    }

    /// Path to the skeleton (.bon) file.
    #[wasm_bindgen(getter, js_name = "skeletonPath")]
    pub fn skeleton_path(&self) -> String {
        self.inner.skeleton_path.clone()
    }

    /// Skin file paths referenced by this model.
    #[wasm_bindgen(getter, js_name = "skinPaths")]
    pub fn skin_paths(&self) -> Vec<String> {
        self.inner.skin_paths.clone()
    }

    /// SMD version number.
    #[wasm_bindgen(getter)]
    pub fn version(&self) -> u32 {
        self.inner.version
    }

    /// Track set directory name (e.g. "tcks_fallen_general").
    /// Present for SMD version >= 8; `undefined` for older versions.
    #[wasm_bindgen(getter, js_name = "tcksDir")]
    pub fn tcks_dir(&self) -> Option<String> {
        self.inner.tcks_dir.clone()
    }
}

/// Parse a BON skeleton file from bytes. Returns a `Skeleton` — TS types
/// are generated by `tsify-next` from the Rust definitions in
/// `autoangel_core::model::bon`.
#[wasm_bindgen(js_name = "parseSkeleton")]
pub fn parse_skeleton(data: &[u8]) -> Result<autoangel_core::model::bon::Skeleton, JsError> {
    let ds = DataSource::from_bytes(data.to_vec());
    pollster::block_on(autoangel_core::model::bon::Skeleton::parse(&ds))
        .map_err(|e| crate::format_error(&e))
}

/// Parsed SKI (skin) file containing meshes, textures, and materials.
#[wasm_bindgen]
pub struct Skin {
    inner: autoangel_core::model::ski::Skin,
}

#[wasm_bindgen]
impl Skin {
    /// Parse a SKI skin file from bytes.
    #[wasm_bindgen]
    pub fn parse(data: &[u8]) -> Result<Skin, JsError> {
        let ds = DataSource::from_bytes(data.to_vec());
        let inner = pollster::block_on(autoangel_core::model::ski::Skin::parse(&ds))
            .map_err(|e| crate::format_error(&e))?;
        Ok(Skin { inner })
    }

    /// Number of skin (weighted/skeletal) meshes.
    #[wasm_bindgen(getter, js_name = "skinMeshCount")]
    pub fn skin_mesh_count(&self) -> usize {
        self.inner.skin_meshes.len()
    }

    /// Number of rigid (static) meshes.
    #[wasm_bindgen(getter, js_name = "rigidMeshCount")]
    pub fn rigid_mesh_count(&self) -> usize {
        self.inner.rigid_meshes.len()
    }

    /// Texture paths used by this skin.
    #[wasm_bindgen(getter)]
    pub fn textures(&self) -> Vec<String> {
        self.inner.textures.clone()
    }

    /// Bone names referenced by this skin (for remapping vertex bone indices to skeleton order).
    #[wasm_bindgen(getter, js_name = "boneNames")]
    pub fn bone_names(&self) -> Vec<String> {
        self.inner.bone_names.clone()
    }

    /// Total skeleton bone count from the header (identity remap range for SKI version < 9).
    #[wasm_bindgen(getter, js_name = "numSkeBone")]
    pub fn num_ske_bone(&self) -> u32 {
        self.inner.num_ske_bone
    }

    // ---- Skin mesh accessors ----

    /// Get the name of skin mesh at the given index.
    #[wasm_bindgen(js_name = "skinMeshName")]
    pub fn skin_mesh_name(&self, index: usize) -> Option<String> {
        self.inner.skin_meshes.get(index).map(|m| m.name.clone())
    }

    /// Get the texture index of skin mesh at the given index (-1 if out of bounds).
    #[wasm_bindgen(js_name = "skinMeshTextureIndex")]
    pub fn skin_mesh_texture_index(&self, index: usize) -> i32 {
        self.inner
            .skin_meshes
            .get(index)
            .map_or(-1, |m| m.texture_index)
    }

    /// Get the material index of skin mesh at the given index (-1 if out of bounds).
    #[wasm_bindgen(js_name = "skinMeshMaterialIndex")]
    pub fn skin_mesh_material_index(&self, index: usize) -> i32 {
        self.inner
            .skin_meshes
            .get(index)
            .map_or(-1, |m| m.material_index)
    }

    /// Get flat vertex positions [x,y,z,x,y,z,...] for skin mesh at the given index.
    #[wasm_bindgen(js_name = "skinMeshPositions")]
    pub fn skin_mesh_positions(&self, index: usize) -> Option<Vec<f32>> {
        self.inner
            .skin_meshes
            .get(index)
            .map(|m| m.vertices.iter().flat_map(|v| v.position).collect())
    }

    /// Get flat vertex normals [nx,ny,nz,...] for skin mesh at the given index.
    #[wasm_bindgen(js_name = "skinMeshNormals")]
    pub fn skin_mesh_normals(&self, index: usize) -> Option<Vec<f32>> {
        self.inner
            .skin_meshes
            .get(index)
            .map(|m| m.vertices.iter().flat_map(|v| v.normal).collect())
    }

    /// Get flat UV coordinates [u,v,u,v,...] for skin mesh at the given index.
    #[wasm_bindgen(js_name = "skinMeshUvs")]
    pub fn skin_mesh_uvs(&self, index: usize) -> Option<Vec<f32>> {
        self.inner
            .skin_meshes
            .get(index)
            .map(|m| m.vertices.iter().flat_map(|v| [v.u, v.v]).collect())
    }

    /// Get triangle indices for skin mesh at the given index.
    #[wasm_bindgen(js_name = "skinMeshIndices")]
    pub fn skin_mesh_indices(&self, index: usize) -> Option<Vec<u16>> {
        self.inner.skin_meshes.get(index).map(|m| m.indices.clone())
    }

    /// Get flat bone weights [w0,w1,w2,w3,...] for skin mesh at the given index.
    /// w3 is computed as max(0, 1 - w0 - w1 - w2) to handle float precision.
    #[wasm_bindgen(js_name = "skinMeshBoneWeights")]
    pub fn skin_mesh_bone_weights(&self, index: usize) -> Option<Vec<f32>> {
        self.inner.skin_meshes.get(index).map(|m| {
            m.vertices
                .iter()
                .flat_map(|v| {
                    let w3 = (1.0 - v.weights[0] - v.weights[1] - v.weights[2]).max(0.0);
                    [v.weights[0], v.weights[1], v.weights[2], w3]
                })
                .collect()
        })
    }

    /// Get flat bone indices [i0,i1,i2,i3,...] for skin mesh at the given index.
    #[wasm_bindgen(js_name = "skinMeshBoneIndices")]
    pub fn skin_mesh_bone_indices(&self, index: usize) -> Option<Vec<u8>> {
        self.inner
            .skin_meshes
            .get(index)
            .map(|m| m.vertices.iter().flat_map(|v| v.bone_indices).collect())
    }

    // ---- Rigid mesh accessors ----

    /// Get the name of rigid mesh at the given index.
    #[wasm_bindgen(js_name = "rigidMeshName")]
    pub fn rigid_mesh_name(&self, index: usize) -> Option<String> {
        self.inner.rigid_meshes.get(index).map(|m| m.name.clone())
    }

    /// Get the bone index of rigid mesh at the given index (-1 if out of bounds).
    #[wasm_bindgen(js_name = "rigidMeshBoneIndex")]
    pub fn rigid_mesh_bone_index(&self, index: usize) -> i32 {
        self.inner
            .rigid_meshes
            .get(index)
            .map_or(-1, |m| m.bone_index)
    }

    /// Get the texture index of rigid mesh at the given index (-1 if out of bounds).
    #[wasm_bindgen(js_name = "rigidMeshTextureIndex")]
    pub fn rigid_mesh_texture_index(&self, index: usize) -> i32 {
        self.inner
            .rigid_meshes
            .get(index)
            .map_or(-1, |m| m.texture_index)
    }

    /// Get the material index of rigid mesh at the given index (-1 if out of bounds).
    #[wasm_bindgen(js_name = "rigidMeshMaterialIndex")]
    pub fn rigid_mesh_material_index(&self, index: usize) -> i32 {
        self.inner
            .rigid_meshes
            .get(index)
            .map_or(-1, |m| m.material_index)
    }

    /// Get flat vertex positions [x,y,z,x,y,z,...] for rigid mesh at the given index.
    #[wasm_bindgen(js_name = "rigidMeshPositions")]
    pub fn rigid_mesh_positions(&self, index: usize) -> Option<Vec<f32>> {
        self.inner
            .rigid_meshes
            .get(index)
            .map(|m| m.vertices.iter().flat_map(|v| v.position).collect())
    }

    /// Get flat vertex normals [nx,ny,nz,...] for rigid mesh at the given index.
    #[wasm_bindgen(js_name = "rigidMeshNormals")]
    pub fn rigid_mesh_normals(&self, index: usize) -> Option<Vec<f32>> {
        self.inner
            .rigid_meshes
            .get(index)
            .map(|m| m.vertices.iter().flat_map(|v| v.normal).collect())
    }

    /// Get flat UV coordinates [u,v,u,v,...] for rigid mesh at the given index.
    #[wasm_bindgen(js_name = "rigidMeshUvs")]
    pub fn rigid_mesh_uvs(&self, index: usize) -> Option<Vec<f32>> {
        self.inner
            .rigid_meshes
            .get(index)
            .map(|m| m.vertices.iter().flat_map(|v| [v.u, v.v]).collect())
    }

    /// Get triangle indices for rigid mesh at the given index.
    #[wasm_bindgen(js_name = "rigidMeshIndices")]
    pub fn rigid_mesh_indices(&self, index: usize) -> Option<Vec<u16>> {
        self.inner
            .rigid_meshes
            .get(index)
            .map(|m| m.indices.clone())
    }
}

/// Parse a BMD ("MOXB"-prefixed A3DLitModel) file from bytes. Returns a
/// `BmdModel` — TypeScript types are generated by `tsify-next` from the
/// Rust definitions in `autoangel_core::model::bmd`.
#[wasm_bindgen(js_name = "parseBmd")]
pub fn parse_bmd(data: &[u8]) -> Result<autoangel_core::model::bmd::BmdModel, JsError> {
    let ds = DataSource::from_bytes(data.to_vec());
    pollster::block_on(autoangel_core::model::bmd::BmdModel::parse(&ds))
        .map_err(|e| crate::format_error(&e))
}

/// Parse a STCK animation file from bytes. Returns an `Animation` — TS types
/// are generated by `tsify-next` from the Rust definitions in
/// `autoangel_core::model::stck`.
#[wasm_bindgen(js_name = "parseAnimation")]
pub fn parse_animation(data: &[u8]) -> Result<autoangel_core::model::stck::Animation, JsError> {
    let ds = DataSource::from_bytes(data.to_vec());
    pollster::block_on(autoangel_core::model::stck::Animation::parse(&ds))
        .map_err(|e| crate::format_error(&e))
}
